language: c

os:
  - osx

osx_image: xcode9.2

compiler:
  - clang

sudo: false

env:
  - VIMCMD=/usr/local/Cellar/macvim/HEAD-*/MacVim.app/Contents/MacOS/Vim

script:
  - brew update || brew update
  - brew tap macvim-dev/macvim
  - brew install ruby
  - brew install --HEAD macvim-dev/macvim/macvim || true
  - rm -f result; $VIMCMD -g -f -c "redir>result" -c "lua print(\"Test\")" -c "redir END" -c q; cat result; echo; grep -q -w Test result
  - rm -f result; $VIMCMD -g -f -c "redir>result" -c "perl VIM::Msg(\"Test\")" -c "redir END" -c q; cat result; echo; grep -q -w Test result
  - rm -f result; $VIMCMD -g -f -c "redir>result" -c "py print(\"Test\")" -c "redir END" -c q; cat result; echo; grep -q -w Test result
  - rm -f result; $VIMCMD -g -f -c "redir>result" -c "py3 print(\"Test\")" -c "redir END" -c q; cat result; echo; grep -q -w Test result
  - rm -f result; $VIMCMD -g -f -c "redir>result" -c "ruby puts(\"Test\")" -c "redir END" -c q; cat result; echo; grep -q -w Test result

# vim:set sts=2 sw=2 tw=0 et:
